language: node_js
node_js:
  - "0.12"
services:
  - mongodb
notifications:
  email: false
script:
  - npm test
after_script:
  - npm run cov
env:
  global:
    # FIREBASE_TOKEN
    - secure: PlI7CjQeOIiCzEpxxqi7NgTBBB09P//9/Ec+d+Ln5iyBWhaeufDbgpTJyqhmKEhdP2dGAFH0OBqW9obJMR4qGw2P8d1jTqNHA1X93tFPPsaYIEJ9C3zgB4pxPs070luFZrtBlXO+wEV3Imvv/8Ee6MF0X3hlxegcjbkfgEn6ixKRrs9fuFLET5xtOLXTvVhnPbX3KkqPrsqiwaKHMHlu8tbMml/dU6Luq84dJmM8BVnpGr5QC+R/Bp4Ccf2Ld3Q2fpM5BPtk5O+QMd48OwhlaKlTmEX8QwREEEMa8/Izoe7bDMat0VhwaK6iJbAzssea/qEU64VzmZM3SLZwa7UawNFRylejVgtzHN1xpOUuvY/HUrqV95YnirSc09LuJh8Tc+VD5IkmOM0u+0E8L1YbSXlBA+1XwickWU4/wisyCd62uWBZfsuqdhDJeObqNJL0FxhvUdZzrqWT6trPevyuZtBQWQzxsHWbz2fbtZEUucVUBcVmEgvFDPy9FIDEi7oSGsSFWoqJu05JntecAQRCzGc5FgOXxA1yBMXy1TgyhHxWrUqcl/oK1JRRlgS9fqWESF0EZhdTNVO9lZQ+OnHQLLaJslQBQJSGhwUDlmgAwK/1+2r+v2NEQ9EZmTLnb20mDKYrc27GS04/wOWN6zwrca1ZtHgiU+N4k+LaHvq/xq0=
    # FIREBASE_SECRET
    - secure: mZ4R5EsiIt7QoDomtV7mjP7RIGkWkhr3SoM1YxggXoQ/QrKBaFjewT/EBogAqnLsyZLc0pvXtd49P9pSUW8DpA8JD8PZyq/F1MQKUpg3D95+Q0j4qU1d1oa3uuvp3SRGcME9QTROmxDXGhdmdLt5Lq3scHyOS/w702+MEJCC2AVlDQ/Ugx411pg7DLyi11FML5BrmnDMgrxpx4W6/D1wEbpMmjj4vOEgqGUVD3iLGacFHBHw2OO5crIG0nFuvgm7NLtLLeZ2xSp5wu8sD218u6OfmAmKTHuVdj3GgXerwmrAWtdkBREp+WfA/EHtX1wEQLR9iX7Ev/Udi4KlE47/VbKx7DzJpFmerzpW5jjaLG65wJHEQN6X4uKze02gfA6M8wLSTqv7cy4NwUmZeIa7+nwoHAHylQdP2WR7lHaIoGrYn0LQ4nsVt5GBArADsKMcauF48g7OcroY/awtV+MW4OBU0nEMqkIOAf6ALCc8PFA6Ds4Jmdd6WrNz7IeRTzSRxvxnhSHYLUYEp6he7h1a++JsUIaRiZEvorhWujdvFW/e58lFTeavAyXUopyQmWSalD/kaUSTCTU0c+e2TpxUqkSYIE/9fPT2vnB8R480uBRfLEVjMfmQ30GZw45nySrgXLw4qpv4Spf9R0M6lJPD/T1tPfE4eATPTs/st1Qvah4=
